#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_FINGERPRINT_FPSENSOR_JC_TEE) += fpsensor_jc_tee/
obj-$(CONFIG_SUNWAVE_TEE_FINGERPRINT) += sunwave_fp_tee/
obj-$(CONFIG_FPC_REE_FINGERPRINT) += fpc_ree/
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_FINGERPRINT_MICROARRAY_FP) += microarray/
obj-$(CONFIG_FINGERPRINT_CDFINGER_FP) += cdfinger_fp_tee/
obj-$(CONFIG_FINGERPRINT_BLESTECH) += betterlife/
obj-$(CONFIG_FINGERPRINT_CDFINGER_FP_REE) += cdfinger_fp_ree/
